excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

line_length: 150
force_cast: warning

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - _fetchedResultsController
